### PR TITLE
increase body size for opencv

### PR DESCRIPTION
**Pull request by hellonico**
adding a rule for a higher size limit to the group opencv instead of opencv-native as I am not able to use opencv-native even on a new barebone leiningen project.

```
Username: hellonico
Password: 
Created /Users/niko/origami-land/opencv-build/clojars/opencv-native/target/opencv-native-0.1.0.jar
Wrote /Users/niko/origami-land/opencv-build/clojars/opencv-native/pom.xml
Need to sign 2 files with GPG
[1/2] Signing /Users/niko/origami-land/opencv-build/clojars/opencv-native/target/opencv-native-0.1.0.jar with GPG
[2/2] Signing /Users/niko/origami-land/opencv-build/clojars/opencv-native/pom.xml with GPG
Sending opencv-native/opencv-native/0.1.0/opencv-native-0.1.0.jar (9k)
    to https://repo.clojars.org/
Could not transfer artifact opencv-native:opencv-native:jar:0.1.0 from/to releases (https://repo.clojars.org): Failed to transfer file: https://repo.clojars.org/opencv-native/opencv-native/0.1.0/opencv-native-0.1.0.jar. Return code is: 405, ReasonPhrase: Not Allowed.
Sending opencv-native/opencv-native/0.1.0/opencv-native-0.1.0.pom (2k)
    to https://repo.clojars.org/
Could not transfer artifact opencv-native:opencv-native:pom:0.1.0 from/to releases (https://repo.clojars.org): Failed to transfer file: https://repo.clojars.org/opencv-native/opencv-native/0.1.0/opencv-native-0.1.0.pom. Return code is: 405, ReasonPhrase: Not Allowed.
Sending opencv-native/opencv-native/0.1.0/opencv-native-0.1.0.jar.asc (1k)
    to https://repo.clojars.org/
Could not transfer artifact opencv-native:opencv-native:jar.asc:0.1.0 from/to releases (https://repo.clojars.org): Failed to transfer file: https://repo.clojars.org/opencv-native/opencv-native/0.1.0/opencv-native-0.1.0.jar.asc. Return code is: 405, ReasonPhrase: Not Allowed.
Sending opencv-native/opencv-native/0.1.0/opencv-native-0.1.0.pom.asc (1k)
    to https://repo.clojars.org/
Could not transfer artifact opencv-native:opencv-native:pom.asc:0.1.0 from/to releases (https://repo.clojars.org): Failed to transfer file: https://repo.clojars.org/opencv-native/opencv-native/0.1.0/opencv-native-0.1.0.pom.asc. Return code is: 405, ReasonPhrase: Not Allowed.
Failed to deploy artifacts: Could not transfer artifact opencv-native:opencv-native:jar:0.1.0 from/to releases (https://repo.clojars.org): Failed to transfer file: https://repo.clojars.org/opencv-native/opencv-native/0.1.0/opencv-native-0.1.0.jar. Return code is: 405, ReasonPhrase: Not Allowed.
```

### CODE REVIEW

**Comment by hellonico** [comment]
Re: your question on: https://github.com/clojars/clojars-server-config/pull/45

I tried again today with an almost empty SNAPSHOT jar file:

```
SuperPinkicious:clojars niko$ jar tvf opencv-native-4.0.0-1-SNAPSHOT.jar 
     0 Mon May 27 14:17:28 JST 2019 META-INF/
    69 Mon May 27 14:17:28 JST 2019 META-INF/MANIFEST.MF
     0 Mon May 27 14:17:22 JST 2019 test
``` 

With same result:
```
Caused by: org.apache.maven.wagon.TransferFailedException: Failed to transfer file: https://clojars.org/repo/opencv-native/opencv-native/4.0.0-1-SNAPSHOT/opencv-native-4.0.0-1-20190527.051828-1.jar. Return code is: 405, ReasonPhrase: Not Allowed.
 at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put (AbstractHttpClientWagon.java:635)
    org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put (AbstractHttpClientWagon.java:557)
```

**Comment by tobias** [comment]
Hi @hellonico - sorry this isn't working, thanks for continuing to dig in to it. I did some looking this morning, and don't have any idea why this is happening yet. I'd like to catalog what we know currently along with open questions. Please correct any assumptions below if they are incorrect:

- This doesn't appear to be an issue with the CDN, since your latest SNAPSHOT attempt went directly to https://clojars.org
- You can deploy other artifacts that aren't named `opencv-native` using the exact same command without issue
- I've looked through the error logs on the server and don't see any errors related to your deploy attempt
- I can see the upload attempt in the access.log (though I see it is sending a `.xml` file instead of `.pom` - what command are you using to upload? The xml file shouldn't matter, since the jar file is getting rejected *before* the xml file is uploaded):

```
<ip redacted> - hellonico [27/May/2019:05:18:29 +0000] "PUT /repo/opencv-native/opencv-native/4.0.0-1-SNAPSHOT/opencv-native-4.0.0-1-20190527.051828-1.jar HTTP/1.1" 405 166 "-" "Leiningen/2.9.1 (Java Java HotSpot(TM) 64-Bit Server VM; Mac OS X 10.14.3; x86_64)"
<ip redacted> - hellonico [27/May/2019:05:18:30 +0000] "PUT /repo/opencv-native/opencv-native/4.0.0-1-SNAPSHOT/opencv-native-4.0.0-1-20190527.051828-1.xml HTTP/1.1" 405 166 "-" "Leiningen/2.9.1 (Java Java HotSpot(TM) 64-Bit Server VM; Mac OS X 10.14.3; x86_64)"
```

- We have only one spot where we explicitly return a 405 that we know of: https://github.com/clojars/clojars-web/blob/master/src/clojars/web.clj#L91, but that should only get hit if the path *isn't* `/repo`
- We do have a check for reserved group names, but `opencv-native` isn't on that list, and that should return a `403`
- We also check maven central to prevent shadowing, but `opencv-native/opencv-native` doesn't exist there, and that would also return a `403`
- No `opencv-native` group exists in the clojars db belonging to a different user

If you are willing to run some more experiments, can you:

- try the snapshot upload you tried above, but share the command you used to do it and the full output? I'll then look to see if we create a temp dir for the upload - that will tell us how far in to the deploy process it gets, and those dirs get cleaned up after 24 hours if the deploy fails, so we no longer have the one from your last attempt.

**Comment by hellonico** [comment]
Using leiningen debug mode and just removed the password from the logs below ...
At the bottom of the log we can see the *PUT* method being used.
You can probably try the same on any jar/pom combination on your side with the same command.  


```
SuperPinkicious:clojars niko$ lein -version 
Leiningen 2.9.1 on Java 1.8.0_191 Java HotSpot(TM) 64-Bit Server VM

SuperPinkicious:clojars niko$ java -version 
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

SuperPinkicious:clojars niko$ export DEBUG=y 

SuperPinkicious:clojars niko$ lein deploy clojars opencv-native/opencv-native 4.0.0-1-SNAPSHOT opencv-native-4.0.0-1-SNAPSHOT.jar opencv-native-4.0.0-1-SNAPSHOT.pom.xml
Leiningen's classpath: /Users/niko/.lein/self-installs/leiningen-2.9.1-standalone.jar
Applying task deploy to [clojars opencv-native/opencv-native 4.0.0-1-SNAPSHOT opencv-native-4.0.0-1-SNAPSHOT.jar opencv-native-4.0.0-1-SNAPSHOT.pom.xml]
Deploying (opencv-native-4.0.0-1-SNAPSHOT.jar opencv-native-4.0.0-1-SNAPSHOT.pom.xml) to [clojars {:url https://clojars.org/repo/, :password tiabtfda8!, :username hellonico}]
Could not find metadata opencv-native:opencv-native:4.0.0-1-SNAPSHOT/maven-metadata.xml in clojars (https://clojars.org/repo/)
Sending opencv-native/opencv-native/4.0.0-1-SNAPSHOT/opencv-native-4.0.0-1-20190529.231234-1.jar (1k)
    to https://clojars.org/repo/
Could not transfer artifact opencv-native:opencv-native:jar:4.0.0-1-20190529.231234-1 from/to clojars (https://clojars.org/repo/): Failed to transfer file: https://clojars.org/repo/opencv-native/opencv-native/4.0.0-1-SNAPSHOT/opencv-native-4.0.0-1-20190529.231234-1.jar. Return code is: 405, ReasonPhrase: Not Allowed.
Sending opencv-native/opencv-native/4.0.0-1-SNAPSHOT/opencv-native-4.0.0-1-20190529.231234-1.xml (1k)
    to https://clojars.org/repo/
Could not transfer artifact opencv-native:opencv-native:xml:4.0.0-1-20190529.231234-1 from/to clojars (https://clojars.org/repo/): Failed to transfer file: https://clojars.org/repo/opencv-native/opencv-native/4.0.0-1-SNAPSHOT/opencv-native-4.0.0-1-20190529.231234-1.xml. Return code is: 405, ReasonPhrase: Not Allowed.
org.eclipse.aether.deployment.DeploymentException: Failed to deploy artifacts: Could not transfer artifact opencv-native:opencv-native:jar:4.0.0-1-20190529.231234-1 from/to clojars (https://clojars.org/repo/): Failed to transfer file: https://clojars.org/repo/opencv-native/opencv-native/4.0.0-1-SNAPSHOT/opencv-native-4.0.0-1-20190529.231234-1.jar. Return code is: 405, ReasonPhrase: Not Allowed.
 at org.eclipse.aether.internal.impl.DefaultDeployer.deploy (DefaultDeployer.java:295)
    org.eclipse.aether.internal.impl.DefaultDeployer.deploy (DefaultDeployer.java:223)
    org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy (DefaultRepositorySystem.java:384)
    sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
    sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke (Method.java:498)
    clojure.lang.Reflector.invokeMatchingMethod (Reflector.java:167)
    clojure.lang.Reflector.invokeInstanceMethod (Reflector.java:102)
    cemerick.pomegranate.aether$deploy_artifacts.invokeStatic (aether.clj:358)
    cemerick.pomegranate.aether$deploy_artifacts.doInvoke (aether.clj:308)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.core$apply.invoke (core.clj:660)
    cemerick.pomegranate.aether$deploy.invokeStatic (aether.clj:427)
    cemerick.pomegranate.aether$deploy.doInvoke (aether.clj:391)
    clojure.lang.RestFn.invoke (RestFn.java:805)
    leiningen.deploy$deploy.invokeStatic (deploy.clj:234)
    leiningen.deploy$deploy.doInvoke (deploy.clj:172)
    clojure.lang.RestFn.applyTo (RestFn.java:151)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.main$partial_task$fn__6592.doInvoke (main.clj:284)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:31)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.main$apply_task.invokeStatic (main.clj:334)
    leiningen.core.main$apply_task.invoke (main.clj:320)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:343)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:336)
    leiningen.core.main$_main$fn__6681.invoke (main.clj:452)
    leiningen.core.main$_main.invokeStatic (main.clj:442)
    leiningen.core.main$_main.doInvoke (main.clj:439)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.main$main_opt.invokeStatic (main.clj:491)
    clojure.main$main_opt.invoke (main.clj:487)
    clojure.main$main.invokeStatic (main.clj:598)
    clojure.main$main.doInvoke (main.clj:561)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.main.main (main.java:37)
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact opencv-native:opencv-native:jar:4.0.0-1-20190529.231234-1 from/to clojars (https://clojars.org/repo/): Failed to transfer file: https://clojars.org/repo/opencv-native/opencv-native/4.0.0-1-SNAPSHOT/opencv-native-4.0.0-1-20190529.231234-1.jar. Return code is: 405, ReasonPhrase: Not Allowed.
 at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed (ArtifactTransportListener.java:52)
    org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:364)
    org.eclipse.aether.connector.basic.BasicRepositoryConnector.put (BasicRepositoryConnector.java:283)
    org.eclipse.aether.internal.impl.DefaultDeployer.deploy (DefaultDeployer.java:289)
    org.eclipse.aether.internal.impl.DefaultDeployer.deploy (DefaultDeployer.java:223)
    org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy (DefaultRepositorySystem.java:384)
    sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
    sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke (Method.java:498)
    clojure.lang.Reflector.invokeMatchingMethod (Reflector.java:167)
    clojure.lang.Reflector.invokeInstanceMethod (Reflector.java:102)
    cemerick.pomegranate.aether$deploy_artifacts.invokeStatic (aether.clj:358)
    cemerick.pomegranate.aether$deploy_artifacts.doInvoke (aether.clj:308)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.core$apply.invoke (core.clj:660)
    cemerick.pomegranate.aether$deploy.invokeStatic (aether.clj:427)
    cemerick.pomegranate.aether$deploy.doInvoke (aether.clj:391)
    clojure.lang.RestFn.invoke (RestFn.java:805)
    leiningen.deploy$deploy.invokeStatic (deploy.clj:234)
    leiningen.deploy$deploy.doInvoke (deploy.clj:172)
    clojure.lang.RestFn.applyTo (RestFn.java:151)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.main$partial_task$fn__6592.doInvoke (main.clj:284)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:31)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.main$apply_task.invokeStatic (main.clj:334)
    leiningen.core.main$apply_task.invoke (main.clj:320)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:343)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:336)
    leiningen.core.main$_main$fn__6681.invoke (main.clj:452)
    leiningen.core.main$_main.invokeStatic (main.clj:442)
    leiningen.core.main$_main.doInvoke (main.clj:439)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.main$main_opt.invokeStatic (main.clj:491)
    clojure.main$main_opt.invoke (main.clj:487)
    clojure.main$main.invokeStatic (main.clj:598)
    clojure.main$main.doInvoke (main.clj:561)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.main.main (main.java:37)
Caused by: org.apache.maven.wagon.TransferFailedException: Failed to transfer file: https://clojars.org/repo/opencv-native/opencv-native/4.0.0-1-SNAPSHOT/opencv-native-4.0.0-1-20190529.231234-1.jar. Return code is: 405, ReasonPhrase: Not Allowed.
 at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put (AbstractHttpClientWagon.java:635)
    org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put (AbstractHttpClientWagon.java:557)
    org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put (AbstractHttpClientWagon.java:539)
    org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put (AbstractHttpClientWagon.java:533)
    org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put (AbstractHttpClientWagon.java:513)
    org.eclipse.aether.transport.wagon.WagonTransporter$PutTaskRunner.run (WagonTransporter.java:653)
    org.eclipse.aether.transport.wagon.WagonTransporter.execute (WagonTransporter.java:436)
    org.eclipse.aether.transport.wagon.WagonTransporter.put (WagonTransporter.java:419)
    org.eclipse.aether.connector.basic.BasicRepositoryConnector$PutTaskRunner.runTask (BasicRepositoryConnector.java:519)
    org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:359)
    org.eclipse.aether.connector.basic.BasicRepositoryConnector.put (BasicRepositoryConnector.java:283)
    org.eclipse.aether.internal.impl.DefaultDeployer.deploy (DefaultDeployer.java:289)
    org.eclipse.aether.internal.impl.DefaultDeployer.deploy (DefaultDeployer.java:223)
    org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy (DefaultRepositorySystem.java:384)
    sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
    sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke (Method.java:498)
    clojure.lang.Reflector.invokeMatchingMethod (Reflector.java:167)
    clojure.lang.Reflector.invokeInstanceMethod (Reflector.java:102)
    cemerick.pomegranate.aether$deploy_artifacts.invokeStatic (aether.clj:358)
    cemerick.pomegranate.aether$deploy_artifacts.doInvoke (aether.clj:308)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.core$apply.invoke (core.clj:660)
    cemerick.pomegranate.aether$deploy.invokeStatic (aether.clj:427)
    cemerick.pomegranate.aether$deploy.doInvoke (aether.clj:391)
    clojure.lang.RestFn.invoke (RestFn.java:805)
    leiningen.deploy$deploy.invokeStatic (deploy.clj:234)
    leiningen.deploy$deploy.doInvoke (deploy.clj:172)
    clojure.lang.RestFn.applyTo (RestFn.java:151)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.main$partial_task$fn__6592.doInvoke (main.clj:284)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:31)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.main$apply_task.invokeStatic (main.clj:334)
    leiningen.core.main$apply_task.invoke (main.clj:320)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:343)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:336)
    leiningen.core.main$_main$fn__6681.invoke (main.clj:452)
    leiningen.core.main$_main.invokeStatic (main.clj:442)
    leiningen.core.main$_main.doInvoke (main.clj:439)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.main$main_opt.invokeStatic (main.clj:491)
    clojure.main$main_opt.invoke (main.clj:487)
    clojure.main$main.invokeStatic (main.clj:598)
    clojure.main$main.doInvoke (main.clj:561)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.main.main (main.java:37)
```

**Comment by tobias** [comment]
I believe I see the issue - [`proxy_pass` isn't inherited from a parent `location` block in nginx](https://forum.nginx.org/read.php?2,243488,243493#msg-243493), so setting just `client_max_body_size` in the nested `location` directive causes requests to that path to be rejected. So I think the `proxy_pass` (and possibly the full `limit_except`) directive will need to be copied in to the nested locations.

**Comment by hellonico** [comment]
So something like this ?

```
location /repo {
...
location /repo/opencv-native {
       client_max_body_size 100m;
       limit_except GET HEAD {
        # send uploads to webapp
        proxy_pass http://clojars-web;
      }
    }
...
}
```

**Comment by hellonico** [comment]
I've just modified the PR accordingly. 
I also removed the extra limit on opencv (only keeping opencv-native)

**Comment by hellonico** [comment]
Any update ?

**Comment by hellonico** [comment]
Hi Tobias,
Has the PR been handled or just closed ?

Nico

**Comment by tobias** [comment]
Hi @hellonico! I was doing branch cleanup and renamed `master` -> `main`. Doing so automatically closed this PR and your comment brought it back to my attention! Apologies for this falling through the cracks. 

The nginx config file has moved to https://github.com/clojars/clojars-server-config/blob/main/aws-ansible/roles/clojars/templates/clojars.nginx.conf.j2 but does not have any additional changes for `opencv-native`.

I just applied a temporary change on the server to match your last suggestion above - if this is still an issue for you, can you test? To be clear, the `opencv-native` directive is currently:

```
location /repo/opencv-native {
  limit_except GET HEAD {
    # send uploads to webapp
    proxy_pass http://clojars-web;
  }
}

**Comment by tobias** [comment]
@hellonico I went ahead and added your change to the configuration here: https://github.com/clojars/clojars-server-config/commit/51e08f9988dd2109ee5360bfd57e46d9d2ede292. Let me know if that doesn't solve the issue for you.

**Comment by hellonico** [comment]
@tobias Thank you so much ! there are a few things i need to check before trying this ! 
but i cannot wait. 
thank you so much.

**Pull request closed without merging**
